import http from 'node:http';
import { URL } from 'node:url';

const PORT = Number(process.env.PORT || 3000);
const API_KEY = String(process.env.BORSA_API_KEY || '').trim();
const PROVIDER = 'BorsaTakipV5 Railway Backend';
const SOURCE = 'Yahoo Finance upstream (capability-preserving)';
const ISTANBUL_TZ = 'Europe/Istanbul';
const MAX_REALTIME_AGE_SECONDS = 5;
const SYMBOLS = ['AKBNK','ALARK','ASELS','ASTOR','BIMAS','BRSAN','CIMSA','DOAS','EKGYO','ENKAI','EREGL','FROTO','GARAN','GUBRF','HEKTS','ISCTR','KCHOL','KONTR','KOZAL','KRDMD','MGROS','OYAKC','PETKM','PGSUS','SAHOL','SASA','SISE','TCELL','THYAO','TOASO','TUPRS','YKBNK','AEFES','ARCLK','CCOLA','ENJSA','MAVI','OTKAR','TAVHL','TTKOM'];
const SYMBOL_SET = new Set(SYMBOLS);
function send(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(body));}
function authOk(req){return !!API_KEY && String(req.headers.authorization||'')===`Bearer ${API_KEY}`;}
function requireAuth(req,res){if(!API_KEY){send(res,503,{ok:false,code:'AUTH_NOT_CONFIGURED'});return false;}if(!authOk(req)){send(res,401,{ok:false,code:'AUTH_ERROR'});return false;}return true;}
function normalizeSymbol(raw){const s=String(raw||'').trim().toUpperCase();if(!/^[A-Z0-9_]{3,12}$/.test(s))throw new Error('INVALID_SYMBOL');if(!SYMBOL_SET.has(s))throw new Error('UNKNOWN_SYMBOL');return s;}
function yahooSymbol(symbol){return `${symbol}.IS`;}
async function fetchJson(url,timeoutMs=12000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{signal:c.signal,headers:{accept:'application/json,text/plain,*/*','user-agent':'Mozilla/5.0 BorsaTakipV5Backend/1.0'}});if(!r.ok)throw new Error(`UPSTREAM_HTTP_${r.status}`);return await r.json();}finally{clearTimeout(t);}}
async function yahooChart(symbol,{range='1y',interval='1d',period1=null,period2=null}={}){const qs=new URLSearchParams({interval,events:'div,splits',includePrePost:'false'});if(period1&&period2){qs.set('period1',String(period1));qs.set('period2',String(period2));}else qs.set('range',range);const path=`/v8/finance/chart/${encodeURIComponent(yahooSymbol(symbol))}?${qs}`;let last;for(const host of ['https://query1.finance.yahoo.com','https://query2.finance.yahoo.com']){try{const j=await fetchJson(host+path);const r=j?.chart?.result?.[0];if(!r)throw new Error(j?.chart?.error?.description||'UPSTREAM_EMPTY');return r;}catch(e){last=e;}}throw last||new Error('UPSTREAM_UNAVAILABLE');}
function istanbulParts(ms=Date.now()){const p=new Intl.DateTimeFormat('en-CA',{timeZone:ISTANBUL_TZ,weekday:'short',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(ms));const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return{weekday:o.weekday,date:`${o.year}-${o.month}-${o.day}`,hour:Number(o.hour),minute:Number(o.minute)};}
function isBistSessionNow(ms=Date.now()){const p=istanbulParts(ms);if(['Sat','Sun'].includes(p.weekday))return false;const m=p.hour*60+p.minute;return m>=600&&m<=1090;}
function chartCandles(r){const ts=Array.isArray(r?.timestamp)?r.timestamp:[];const q=r?.indicators?.quote?.[0]||{};const out=[];for(let i=0;i<ts.length;i++){const o=q.open?.[i],h=q.high?.[i],l=q.low?.[i],c=q.close?.[i],v=q.volume?.[i];if(![o,h,l,c,v].every(x=>Number.isFinite(Number(x))))continue;if(!(o>0&&h>0&&l>0&&c>0&&v>=0&&l<=h&&o>=l&&o<=h&&c>=l&&c<=h))continue;out.push({timestamp:Number(ts[i])*1000,open:Number(o),high:Number(h),low:Number(l),close:Number(c),volume:Number(v)});}return out;}
function quoteFromResult(symbol,r){const m=r?.meta||{};const price=Number(m.regularMarketPrice),prev=Number(m.chartPreviousClose??m.previousClose),ts=Number(m.regularMarketTime||0)*1000;if(!(price>0)||!(ts>0))throw new Error('QUOTE_ERROR');const age=Math.max(0,Math.floor((Date.now()-ts)/1000));const inSession=isBistSessionNow();return{symbol,market:'BIST',price,previousClose:Number.isFinite(prev)&&prev>0?prev:null,bid:null,ask:null,exchangeTimestamp:ts,receivedAt:Date.now(),source:SOURCE,realtime:inSession&&age<=MAX_REALTIME_AGE_SECONDS,delaySeconds:age,currentSessionIncluded:inSession&&age<=60,currency:m.currency||'TRY'};}
function intervalToMs(i){if(i==='1d')return 86400000;const m=/^([0-9]+)m$/.exec(i);return m?Number(m[1])*60000:60000;}
function historyFromResult(symbol,r,interval='1d'){const candles=chartCandles(r);if(!candles.length)throw new Error('NO_CANDLES');const meta=r?.meta||{},last=candles[candles.length-1],nowSession=isBistSessionNow(),today=istanbulParts().date,lastDate=istanbulParts(last.timestamp).date;return{symbol,market:'BIST',name:meta.longName||meta.shortName||symbol,interval,exchangeTimezone:ISTANBUL_TZ,sessionId:today,lastBarTime:last.timestamp,lastBarClosed:interval==='1d'?!(nowSession&&lastDate===today):(Date.now()-last.timestamp>intervalToMs(interval)),currentSessionIncluded:nowSession&&lastDate===today,previousClose:Number(meta.chartPreviousClose??meta.previousClose)||null,candles,source:SOURCE};}
function sanitizeInterval(raw){const x=String(raw||'1d').toLowerCase();if(!new Set(['1m','2m','3m','5m','15m','30m','60m','90m','1d']).has(x))throw new Error('INVALID_INTERVAL');return x;}
function yahooRangeFor(i,r='1y'){if(i==='1m')return'5d';if(i!=='1d')return'1mo';return['1mo','3mo','6mo','1y','2y','5y','10y','max'].includes(r)?r:'1y';}
async function buildPair(symbol){const r=await yahooChart(symbol,{range:'1y',interval:'1d'});return{quote:quoteFromResult(symbol,r),history:historyFromResult(symbol,r,'1d')};}
async function handlePreflight(res){const sampleSymbol='THYAO';const base={authentication:{ok:true,message:'Bearer token accepted.'},symbols:{ok:true,message:`${SYMBOLS.length} BIST symbol available.`},symbolCount:SYMBOLS.length,sampleSymbol,provider:PROVIDER};try{const p=await buildPair(sampleSymbol),q=p.quote,h=p.history;const quoteOk=q.realtime===true&&q.currentSessionIncluded===true&&q.delaySeconds<=MAX_REALTIME_AGE_SECONDS;const historyOk=h.candles.length>=220&&h.lastBarTime===h.candles[h.candles.length-1].timestamp&&!!h.exchangeTimezone;send(res,200,{...base,ok:quoteOk&&historyOk,quote:{ok:quoteOk,message:quoteOk?'Current-session quote is live.':`Upstream quote is not live/current-session (age=${q.delaySeconds}s).`},history:{ok:historyOk,message:historyOk?`${h.candles.length} daily candles validated.`:'History integrity check failed.'},upstream:SOURCE,serverTime:Date.now()});}catch(e){send(res,200,{...base,ok:false,quote:{ok:false,message:String(e.message||e)},history:{ok:false,message:'History unavailable.'},serverTime:Date.now()});}}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),path=u.pathname;if(req.method!=='GET')return send(res,405,{ok:false,code:'METHOD_NOT_ALLOWED'});if(path==='/')return send(res,200,{ok:true,service:PROVIDER,version:'1.0.0',docs:'/v1/health'});if(path==='/v1/health')return send(res,200,{ok:true,provider:PROVIDER,serverTime:Date.now(),message:'Backend ayakta.',upstream:SOURCE,authConfigured:!!API_KEY});if(!requireAuth(req,res))return;if(path==='/v1/preflight')return await handlePreflight(res);if(path==='/v1/bist/symbols')return send(res,200,{items:SYMBOLS,count:SYMBOLS.length,source:SOURCE});let m=/^\/v1\/bist\/quote\/([A-Za-z0-9_]+)$/.exec(path);if(m){try{const s=normalizeSymbol(m[1]),r=await yahooChart(s,{range:'1d',interval:'1m'});return send(res,200,quoteFromResult(s,r));}catch(e){return send(res,502,{ok:false,code:String(e.message||e)});}}m=/^\/v1\/bist\/history\/([A-Za-z0-9_]+)$/.exec(path);if(m){try{const s=normalizeSymbol(m[1]),i=sanitizeInterval(u.searchParams.get('interval')||'1d'),rg=yahooRangeFor(i,u.searchParams.get('range')||'1y'),r=await yahooChart(s,{range:rg,interval:i});return send(res,200,historyFromResult(s,r,i));}catch(e){return send(res,502,{ok:false,code:String(e.message||e)});}}m=/^\/v1\/bist\/history-window\/([A-Za-z0-9_]+)$/.exec(path);if(m){try{const s=normalizeSymbol(m[1]),from=Number(u.searchParams.get('from')),to=Number(u.searchParams.get('to')),i=sanitizeInterval(u.searchParams.get('interval')||'5m');if(!(from>0&&to>from))throw new Error('INVALID_WINDOW');const r=await yahooChart(s,{interval:i,period1:Math.floor(from/1000),period2:Math.floor(to/1000)+1}),h=historyFromResult(s,r,i);h.candles=h.candles.filter(c=>c.timestamp>=from&&c.timestamp<=to);if(!h.candles.length)throw new Error('NO_CANDLES');h.lastBarTime=h.candles[h.candles.length-1].timestamp;return send(res,200,h);}catch(e){return send(res,502,{ok:false,code:String(e.message||e)});}}if(path==='/v1/bist/snapshot-batch'){const reqSymbols=String(u.searchParams.get('symbols')||'').split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);if(!reqSymbols.length||reqSymbols.length>20)return send(res,400,{ok:false,code:'INVALID_BATCH'});const items=await Promise.all(reqSymbols.map(async raw=>{let s;try{s=normalizeSymbol(raw);}catch{return{symbol:raw,error:{code:'EMPTY_DATA',message:'Geçersiz/bilinmeyen sembol.'}};}try{const p=await buildPair(s);return{symbol:s,quote:p.quote,history:p.history};}catch(e){return{symbol:s,error:{code:'SERVER_ERROR',message:String(e.message||e)}};}}));return send(res,200,{items,source:SOURCE});}if(path.startsWith('/v1/viop/'))return send(res,503,{ok:false,code:'VIOP_UPSTREAM_NOT_CONFIGURED',message:'Gerçek VİOP upstream henüz yapılandırılmadı; veri uydurulmadı.'});if(path==='/v1/news')return send(res,200,{items:[],source:'not-configured'});return send(res,404,{ok:false,code:'NOT_FOUND'});}
const server=http.createServer((req,res)=>Promise.resolve(route(req,res)).catch(err=>{console.error(err);if(!res.headersSent)send(res,500,{ok:false,code:'SERVER_ERROR'});else res.end();}));
server.listen(PORT,'0.0.0.0',()=>console.log(`BorsaTakip backend listening on ${PORT}`));
